import React from "react";

// Helpers partagés
function fullName(cv) {
  return cv.nameOrder === "lastFirst"
    ? (cv.lastName + " " + cv.firstName).trim()
    : (cv.firstName + " " + cv.lastName).trim();
}

function CVFooter({ cv, a }) {
  const hasHobbies = cv.hobbies?.filter(h=>h.label).length > 0;
  const hasRefs    = cv.references?.filter(r=>r.name).length > 0;
  const hasSig     = cv.signatureCity || cv.signatureDate;
  const linkedinDisplay = cv.linkedin
    ? cv.linkedin.replace(/https?:\/\/(www\.)?linkedin\.com\/in\//i,"").replace(/\/$/,"")
    : null;
  return (
    <>
      {hasHobbies&&<Sec t="Centres d'intérêt" a={a}><div style={{display:"flex",flexWrap:"wrap",gap:"6px 12px"}}>{cv.hobbies.filter(h=>h.label).map((h,i)=><span key={i} style={{fontSize:10.5,color:"#555",background:`${a}12`,border:`1px solid ${a}25`,borderRadius:20,padding:"2px 10px"}}>{h.label}</span>)}</div></Sec>}
      {cv.certifications?.trim()&&<Sec t="Certifications" a={a}><p style={{fontSize:10.5,color:"#555",margin:0}}>{cv.certifications}</p></Sec>}
      {cv.publications?.trim()&&<Sec t="Publications & Projets" a={a}><p style={{fontSize:10.5,color:"#555",margin:0,whiteSpace:"pre-line"}}>{cv.publications}</p></Sec>}
      {hasRefs&&<Sec t="Références professionnelles" a={a}><div style={{display:"grid",gridTemplateColumns:"repeat(auto-fill,minmax(180px,1fr))",gap:10}}>{cv.references.filter(r=>r.name).map((r,i)=><div key={i} style={{fontSize:10.5,lineHeight:1.7}}><div style={{fontWeight:700,color:"#222"}}>{r.name}</div>{r.role&&<div style={{color:a,fontSize:10}}>{r.role}{r.company?` · ${r.company}`:""}</div>}{r.email&&<div style={{color:"#777",fontSize:9.5}}>{r.email}</div>}{r.phone&&<div style={{color:"#777",fontSize:9.5}}>{r.phone}</div>}</div>)}</div></Sec>}
      {cv.refsOnRequest&&!hasRefs&&<div style={{fontSize:10,color:"#999",fontStyle:"italic",marginTop:8}}>Références disponibles sur demande.</div>}
      {hasSig&&(
        <div style={{marginTop:24}}>
          <div style={{fontSize:9.5,color:"#888",fontStyle:"italic",textAlign:"center",
            border:`1px solid ${a}25`,borderRadius:5,padding:"6px 12px",marginBottom:16,lineHeight:1.6}}>
            Je déclare sur l'honneur que toutes ces informations sont sincères et vérifiables.
          </div>
          <div style={{display:"flex",justifyContent:"flex-end"}}>
            <div style={{textAlign:"right",fontSize:10.5,color:"#888"}}>
              <div>{[cv.signatureCity,cv.signatureDate].filter(Boolean).join(", le ")}</div>
              {cv.signature
                ? <img src={cv.signature} alt="Signature" style={{height:50,marginTop:8,display:"block",marginLeft:"auto"}}/>
                : <div style={{marginTop:28,borderTop:`1px solid ${a}50`,paddingTop:4,fontSize:10,color:"#aaa",minWidth:160}}>Signature</div>}
            </div>
          </div>
        </div>
      )}
      {cv.confidential&&<div style={{position:"absolute",top:"50%",left:"50%",transform:"translate(-50%,-50%) rotate(-30deg)",fontSize:48,fontWeight:900,color:"rgba(0,0,0,0.04)",pointerEvents:"none",letterSpacing:4,textTransform:"uppercase",whiteSpace:"nowrap",zIndex:0}}>CONFIDENTIEL</div>}
      {linkedinDisplay&&<div style={{marginTop:12,textAlign:"right",fontSize:9,color:"#ccc"}}><a href={`https://linkedin.com/in/${linkedinDisplay}`} style={{color:a,textDecoration:"none"}} target="_blank" rel="noopener noreferrer">{cv.firstName} {cv.lastName}</a>{cv.portfolio&&<> · <a href={cv.portfolio} style={{color:a,textDecoration:"none"}} target="_blank" rel="noopener noreferrer">Portfolio</a></>}</div>}
    </>
  );
}

function CVExecutive({ cv }) {
  const a = cv.accentColor || "#c8a96e";
  return <div style={{fontFamily:"'Georgia',serif",background:"#fff",color:"#111",padding:"36px 40px",minHeight:680,position:"relative"}}><div style={{borderBottom:`2.5px solid ${a}`,paddingBottom:16,marginBottom:20,display:"flex",justifyContent:"space-between",alignItems:"flex-start"}}><div style={{flex:1}}><div style={{fontSize:24,fontWeight:700}}>{fullName(cv)}</div><div style={{color:a,fontSize:12,fontWeight:600,marginTop:3}}>{cv.title}</div><div style={{fontSize:9.5,color:"#777",lineHeight:2,marginTop:6}}>{[cv.email,cv.phone,cv.location].filter(Boolean).join("  ·  ")}</div></div>{cv.photo&&<img src={cv.photo} alt="" style={{width:72,height:86,objectFit:"cover",borderRadius:6,marginLeft:16,border:`2px solid ${a}30`}}/>}</div>{cv.summary&&<Sec t="Profil" a={a}><p style={{fontSize:11,lineHeight:1.75,color:"#444",margin:0}}>{cv.summary}</p></Sec>}{cv.experiences?.length>0&&<Sec t="Expériences" a={a}>{cv.experiences.map((e,i)=><ExpBlk key={i} e={e} a={a}/>)}</Sec>}{cv.education?.length>0&&<Sec t="Formation" a={a}>{cv.education.map((e,i)=><EduBlk key={i} e={e}/>)}</Sec>}<div style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:16}}>{cv.skills&&<Sec t="Compétences" a={a}><p style={{fontSize:10.5,color:"#555",margin:0}}>{cv.skills}</p></Sec>}{cv.languages&&<Sec t="Langues" a={a}><p style={{fontSize:10.5,color:"#555",margin:0}}>{cv.languages}</p></Sec>}</div><CVFooter cv={cv} a={a}/></div>;
}
function CVTech({ cv }) {
  return <div style={{fontFamily:"'Courier New',monospace",background:"#020c1b",color:"#8892b0",padding:"36px",minHeight:680,position:"relative"}}><div style={{borderLeft:"3px solid #64ffda",paddingLeft:16,marginBottom:26,display:"flex",gap:16,alignItems:"flex-start"}}><div style={{flex:1}}><div style={{color:"#ccd6f6",fontSize:22,fontWeight:700}}>{fullName(cv)}</div><div style={{color:"#64ffda",fontSize:11,marginTop:3}}>{cv.title}</div><div style={{fontSize:9.5,marginTop:7,color:"#4a5568"}}>{[cv.email,cv.phone,cv.location].filter(Boolean).join(" · ")}</div></div>{cv.photo&&<img src={cv.photo} alt="" style={{width:60,height:72,objectFit:"cover",borderRadius:6,border:"2px solid #64ffda30"}}/>}</div>{cv.summary&&<div style={{marginBottom:18}}><div style={{fontSize:9,color:"#64ffda",marginBottom:5}}>{"// about"}</div><p style={{fontSize:10.5,lineHeight:1.75,margin:0}}>{cv.summary}</p></div>}{cv.experiences?.length>0&&<div style={{marginBottom:18}}><div style={{fontSize:9,color:"#64ffda",marginBottom:9}}>{"// experience"}</div>{cv.experiences.map((e,i)=><div key={i} style={{marginBottom:12}}><div style={{color:"#ccd6f6",fontWeight:700,fontSize:11}}>{e.role} <span style={{color:"#64ffda"}}>@</span> {e.company} <span style={{color:"#4a5568",fontSize:9.5}}>({e.start}–{e.current?"now":e.end})</span></div><p style={{fontSize:10.5,lineHeight:1.65,margin:"3px 0 0"}}>{e.description}</p></div>)}</div>}{cv.education?.length>0&&<div style={{marginBottom:18}}><div style={{fontSize:9,color:"#64ffda",marginBottom:8}}>{"// education"}</div>{cv.education.map((e,i)=><div key={i} style={{fontSize:10.5,marginBottom:6}}><span style={{color:"#ccd6f6"}}>{e.degree} {e.field}</span> — {e.school}</div>)}</div>}{cv.skills&&<div style={{marginBottom:14}}><div style={{fontSize:9,color:"#64ffda",marginBottom:5}}>{"// skills"}</div><p style={{fontSize:10.5,margin:0}}>{cv.skills}</p></div>}<CVFooter cv={cv} a="#64ffda"/></div>;
}
function CVCreative({ cv }) {
  return <div style={{fontFamily:"'Georgia',serif",background:"#fff",minHeight:680,display:"grid",gridTemplateColumns:"180px 1fr",position:"relative"}}><div style={{background:"#1a0a2e",padding:"28px 16px"}}>{cv.photo&&<img src={cv.photo} alt="" style={{width:80,height:96,objectFit:"cover",borderRadius:10,marginBottom:14,border:"2px solid #ff6b9d50"}}/>}<div style={{color:"#fff",fontSize:14,fontWeight:700}}>{fullName(cv)}</div><div style={{color:"#ff6b9d",fontSize:9.5,fontStyle:"italic",marginTop:3}}>{cv.title}</div><div style={{marginTop:18,fontSize:9,color:"#aaa",lineHeight:2.1}}>{[cv.email,cv.phone,cv.location].filter(Boolean).map((v,i)=><div key={i}>{v}</div>)}</div>{cv.skills&&<><div style={{color:"#ff6b9d",fontSize:8,fontWeight:800,textTransform:"uppercase",letterSpacing:2,marginTop:20,marginBottom:8}}>Skills</div><p style={{fontSize:9,color:"#ccc",lineHeight:1.9,margin:0}}>{cv.skills}</p></>}{cv.languages&&<><div style={{color:"#ff6b9d",fontSize:8,fontWeight:800,textTransform:"uppercase",letterSpacing:2,marginTop:14,marginBottom:6}}>Langues</div><p style={{fontSize:9,color:"#ccc",margin:0}}>{cv.languages}</p></>}</div><div style={{padding:"28px 24px"}}>{cv.summary&&<div style={{borderLeft:"3px solid #ff6b9d",paddingLeft:12,marginBottom:16}}><p style={{fontSize:11,color:"#444",lineHeight:1.75,fontStyle:"italic",margin:0}}>{cv.summary}</p></div>}{cv.experiences?.length>0&&<Sec t="Expériences" a="#ff6b9d">{cv.experiences.map((e,i)=><ExpBlk key={i} e={e} a="#ff6b9d"/>)}</Sec>}{cv.education?.length>0&&<Sec t="Formation" a="#ff6b9d">{cv.education.map((e,i)=><EduBlk key={i} e={e}/>)}</Sec>}<CVFooter cv={cv} a="#ff6b9d"/></div></div>;
}
function CVMinimal({ cv }) {
  return <div style={{fontFamily:"'Helvetica Neue',sans-serif",background:"#fff",color:"#111",padding:"44px 40px",minHeight:680,position:"relative"}}><div style={{marginBottom:26,display:"flex",justifyContent:"space-between",alignItems:"flex-start"}}><div><div style={{fontSize:28,fontWeight:200,letterSpacing:4,textTransform:"uppercase"}}>{fullName(cv)}</div><div style={{fontSize:10,letterSpacing:3,textTransform:"uppercase",color:"#aaa",marginTop:5}}>{cv.title}</div><div style={{display:"flex",gap:14,marginTop:10,fontSize:9.5,color:"#bbb"}}>{[cv.email,cv.phone,cv.location].filter(Boolean).map((v,i)=><span key={i}>{v}</span>)}</div></div>{cv.photo&&<img src={cv.photo} alt="" style={{width:64,height:78,objectFit:"cover",borderRadius:4}}/>}</div><div style={{height:1,background:"#eee",marginBottom:24}}/>{cv.summary&&<div style={{marginBottom:24}}><p style={{fontSize:11,color:"#666",lineHeight:1.85,margin:0}}>{cv.summary}</p></div>}{cv.experiences?.length>0&&<div style={{marginBottom:22}}><div style={{fontSize:8,letterSpacing:4,textTransform:"uppercase",color:"#ccc",marginBottom:12}}>Expérience</div>{cv.experiences.map((e,i)=><div key={i} style={{display:"grid",gridTemplateColumns:"100px 1fr",gap:10,marginBottom:12}}><div style={{fontSize:9.5,color:"#ccc",paddingTop:2}}>{e.start}–{e.current?"now":e.end}</div><div><div style={{fontWeight:600,fontSize:11}}>{e.role}</div><div style={{fontSize:10,color:"#aaa"}}>{e.company}</div><p style={{fontSize:10,color:"#777",marginTop:3,lineHeight:1.6,marginBottom:0}}>{e.description}</p></div></div>)}</div>}{cv.education?.length>0&&<div style={{marginBottom:22}}><div style={{fontSize:8,letterSpacing:4,textTransform:"uppercase",color:"#ccc",marginBottom:10}}>Formation</div>{cv.education.map((e,i)=><div key={i} style={{display:"grid",gridTemplateColumns:"100px 1fr",gap:10,marginBottom:9}}><div style={{fontSize:9.5,color:"#ccc"}}>{e.start}–{e.end}</div><div><div style={{fontWeight:600,fontSize:11}}>{e.degree} {e.field}</div><div style={{fontSize:10,color:"#aaa"}}>{e.school}</div></div></div>)}</div>}{cv.skills&&<div style={{marginBottom:14}}><div style={{fontSize:8,letterSpacing:4,textTransform:"uppercase",color:"#ccc",marginBottom:7}}>Compétences</div><p style={{fontSize:10,color:"#777",margin:0}}>{cv.skills}</p></div>}<CVFooter cv={cv} a="#111"/></div>;
}
function CVCorporate({ cv }) {
  return <div style={{fontFamily:"'Georgia',serif",background:"#fff",minHeight:680,position:"relative"}}><div style={{background:"#0d1b2a",padding:"24px 34px",display:"flex",justifyContent:"space-between",alignItems:"center"}}><div><div style={{fontSize:20,fontWeight:700,letterSpacing:1.5,color:"#fff"}}>{fullName(cv).toUpperCase()}</div><div style={{color:"#4fc3f7",fontSize:11,fontWeight:600,marginTop:3}}>{cv.title}</div><div style={{fontSize:9.5,color:"#90a4ae",marginTop:5}}>{[cv.email,cv.phone,cv.location].filter(Boolean).join("  ·  ")}</div></div>{cv.photo&&<img src={cv.photo} alt="" style={{width:62,height:74,objectFit:"cover",borderRadius:6,border:"2px solid #4fc3f730"}}/>}</div><div style={{padding:"24px 34px"}}>{cv.summary&&<Sec t="Synthèse" a="#4fc3f7"><p style={{fontSize:11,lineHeight:1.75,color:"#333",margin:0}}>{cv.summary}</p></Sec>}{cv.experiences?.length>0&&<Sec t="Parcours" a="#4fc3f7">{cv.experiences.map((e,i)=><ExpBlk key={i} e={e} a="#4fc3f7"/>)}</Sec>}{cv.education?.length>0&&<Sec t="Formation" a="#4fc3f7">{cv.education.map((e,i)=><EduBlk key={i} e={e}/>)}</Sec>}<div style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:16}}>{cv.skills&&<Sec t="Compétences" a="#4fc3f7"><p style={{fontSize:10.5,color:"#555",margin:0}}>{cv.skills}</p></Sec>}{cv.languages&&<Sec t="Langues" a="#4fc3f7"><p style={{fontSize:10.5,color:"#555",margin:0}}>{cv.languages}</p></Sec>}</div><CVFooter cv={cv} a="#4fc3f7"/></div></div>;
}
function CVAcademic({ cv }) {
  return <div style={{fontFamily:"'Times New Roman',serif",background:"#fff",color:"#111",padding:"38px",minHeight:680,position:"relative"}}><div style={{textAlign:"center",borderBottom:"2px solid #8b5cf6",paddingBottom:16,marginBottom:20,position:"relative"}}>{cv.photo&&<img src={cv.photo} alt="" style={{width:60,height:72,objectFit:"cover",borderRadius:4,position:"absolute",right:0,top:0}}/>}<div style={{fontSize:21,fontWeight:700}}>{fullName(cv)}</div><div style={{color:"#8b5cf6",fontSize:11,marginTop:3}}>{cv.title}</div><div style={{fontSize:9.5,color:"#888",marginTop:6}}>{[cv.email,cv.phone,cv.location].filter(Boolean).join(" | ")}</div></div>{cv.summary&&<Sec t="Résumé" a="#8b5cf6"><p style={{fontSize:11,lineHeight:1.8,textAlign:"justify",margin:0}}>{cv.summary}</p></Sec>}{cv.experiences?.length>0&&<Sec t="Expériences" a="#8b5cf6">{cv.experiences.map((e,i)=><ExpBlk key={i} e={e} a="#8b5cf6"/>)}</Sec>}{cv.education?.length>0&&<Sec t="Formation Académique" a="#8b5cf6">{cv.education.map((e,i)=><EduBlk key={i} e={e}/>)}</Sec>}{cv.skills&&<Sec t="Compétences" a="#8b5cf6"><p style={{fontSize:10.5,margin:0}}>{cv.skills}</p></Sec>}<CVFooter cv={cv} a="#8b5cf6"/></div>;
}
function CVMedical({ cv }) {
  return <div style={{fontFamily:"'Arial',sans-serif",background:"#fff",minHeight:680,position:"relative"}}><div style={{background:"linear-gradient(135deg,#0a2440,#0d3b6e)",padding:"24px 34px",display:"flex",justifyContent:"space-between",alignItems:"center"}}><div><div style={{fontSize:20,fontWeight:700,color:"#fff"}}>{fullName(cv)}</div><div style={{color:"#34d399",fontSize:11,marginTop:3}}>{cv.title}</div><div style={{fontSize:9.5,color:"#90caf9",marginTop:5}}>{[cv.email,cv.phone,cv.location].filter(Boolean).join("  ·  ")}</div></div>{cv.photo&&<img src={cv.photo} alt="" style={{width:62,height:74,objectFit:"cover",borderRadius:6,border:"2px solid #34d39930"}}/>}</div><div style={{padding:"24px 34px"}}>{cv.summary&&<Sec t="Présentation" a="#34d399"><p style={{fontSize:11,lineHeight:1.75,color:"#333",margin:0}}>{cv.summary}</p></Sec>}{cv.experiences?.length>0&&<Sec t="Expériences" a="#34d399">{cv.experiences.map((e,i)=><ExpBlk key={i} e={e} a="#34d399"/>)}</Sec>}{cv.education?.length>0&&<Sec t="Formation" a="#34d399">{cv.education.map((e,i)=><EduBlk key={i} e={e}/>)}</Sec>}<div style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:16}}>{cv.skills&&<Sec t="Compétences" a="#34d399"><p style={{fontSize:10.5,color:"#555",margin:0}}>{cv.skills}</p></Sec>}{cv.languages&&<Sec t="Langues" a="#34d399"><p style={{fontSize:10.5,color:"#555",margin:0}}>{cv.languages}</p></Sec>}</div><CVFooter cv={cv} a="#34d399"/></div></div>;
}
function CVLegal({ cv }) {
  return <div style={{fontFamily:"'Palatino Linotype',serif",background:"#fffef8",color:"#1a1208",padding:"38px",minHeight:680,position:"relative"}}><div style={{textAlign:"center",marginBottom:24,position:"relative"}}>{cv.photo&&<img src={cv.photo} alt="" style={{width:62,height:74,objectFit:"cover",borderRadius:4,position:"absolute",right:0,top:0,border:"1px solid #b8860b30"}}/>}<div style={{fontSize:9.5,letterSpacing:7,textTransform:"uppercase",color:"#b8860b",marginBottom:7}}>Curriculum Vitæ</div><div style={{fontSize:22,fontWeight:700,letterSpacing:2,textTransform:"uppercase"}}>{fullName(cv)}</div><div style={{color:"#b8860b",fontSize:11,fontStyle:"italic",marginTop:3}}>{cv.title}</div><div style={{width:44,height:1.5,background:"#b8860b",margin:"10px auto"}}/><div style={{fontSize:9.5,color:"#999"}}>{[cv.email,cv.phone,cv.location].filter(Boolean).join("  •  ")}</div></div>{cv.summary&&<Sec t="Profil" a="#b8860b"><p style={{fontSize:11,lineHeight:1.85,textAlign:"justify",margin:0}}>{cv.summary}</p></Sec>}{cv.experiences?.length>0&&<Sec t="Expériences Professionnelles" a="#b8860b">{cv.experiences.map((e,i)=><ExpBlk key={i} e={e} a="#b8860b"/>)}</Sec>}{cv.education?.length>0&&<Sec t="Formation" a="#b8860b">{cv.education.map((e,i)=><EduBlk key={i} e={e}/>)}</Sec>}{cv.skills&&<Sec t="Compétences" a="#b8860b"><p style={{fontSize:10.5,margin:0}}>{cv.skills}</p></Sec>}<CVFooter cv={cv} a="#b8860b"/></div>;
}
function CVMarketing({ cv }) {
  return <div style={{fontFamily:"'Helvetica Neue',sans-serif",background:"#fff",minHeight:680,display:"grid",gridTemplateColumns:"188px 1fr",position:"relative"}}><div style={{background:"#111",padding:"28px 16px"}}>{cv.photo&&<img src={cv.photo} alt="" style={{width:80,height:96,objectFit:"cover",borderRadius:10,marginBottom:12,border:"2px solid #f9731640"}}/>}<div style={{color:"#fff",fontSize:13,fontWeight:800}}>{fullName(cv)}</div><div style={{color:"#f97316",fontSize:9.5,fontWeight:700,textTransform:"uppercase",letterSpacing:1,marginTop:3}}>{cv.title}</div><div style={{marginTop:16,fontSize:9,color:"#888",lineHeight:2.1}}>{[cv.email,cv.phone,cv.location].filter(Boolean).map((v,i)=><div key={i}>{v}</div>)}</div>{cv.skills&&<><div style={{color:"#f97316",fontSize:8,fontWeight:800,textTransform:"uppercase",letterSpacing:2,marginTop:20,marginBottom:8}}>Skills</div>{cv.skills.split(",").map((s,i)=><div key={i} style={{background:"#f9731615",border:"1px solid #f9731430",borderRadius:4,padding:"2px 7px",fontSize:9,color:"#f97316",marginBottom:5}}>{s.trim()}</div>)}</>}{cv.languages&&<><div style={{color:"#f97316",fontSize:8,fontWeight:800,textTransform:"uppercase",letterSpacing:2,marginTop:16,marginBottom:6}}>Langues</div><p style={{fontSize:9,color:"#aaa",margin:0}}>{cv.languages}</p></>}</div><div style={{padding:"28px 24px"}}>{cv.summary&&<div style={{background:"#fff7ed",borderLeft:"3.5px solid #f97316",padding:"10px 12px",borderRadius:"0 8px 8px 0",marginBottom:18}}><p style={{fontSize:11,color:"#555",lineHeight:1.75,margin:0}}>{cv.summary}</p></div>}{cv.experiences?.length>0&&<Sec t="Expériences" a="#f97316">{cv.experiences.map((e,i)=><ExpBlk key={i} e={e} a="#f97316"/>)}</Sec>}{cv.education?.length>0&&<Sec t="Formation" a="#f97316">{cv.education.map((e,i)=><EduBlk key={i} e={e}/>)}</Sec>}<CVFooter cv={cv} a="#f97316"/></div></div>;
}
function CVStartup({ cv }) {
  return <div style={{fontFamily:"'Helvetica Neue',sans-serif",background:"#06060f",color:"#e2e8f0",padding:"34px",minHeight:680,position:"relative"}}><div style={{display:"flex",justifyContent:"space-between",alignItems:"flex-start",marginBottom:24}}><div><div style={{fontSize:22,fontWeight:800,color:"#fff",letterSpacing:"-0.5px"}}>{fullName(cv)}</div><div style={{color:"#818cf8",fontSize:12,fontWeight:600,marginTop:3}}>{cv.title}</div><div style={{fontSize:9.5,color:"#4a5568",marginTop:5}}>{[cv.email,cv.phone,cv.location].filter(Boolean).join(" · ")}</div></div>{cv.photo&&<img src={cv.photo} alt="" style={{width:60,height:72,objectFit:"cover",borderRadius:10,border:"2px solid #818cf830"}}/>}</div>{cv.summary&&<div style={{background:"#0f0f1f",border:"1px solid #818cf825",borderRadius:10,padding:13,marginBottom:20}}><p style={{fontSize:11,color:"#a5b4fc",lineHeight:1.75,margin:0}}>{cv.summary}</p></div>}{cv.experiences?.length>0&&<div style={{marginBottom:18}}><div style={{fontSize:8.5,fontWeight:800,color:"#818cf8",textTransform:"uppercase",letterSpacing:3,marginBottom:10}}>Expériences</div>{cv.experiences.map((e,i)=><div key={i} style={{background:"#0f0f1f",border:"1px solid #1e1e3f",borderRadius:9,padding:11,marginBottom:8}}><div style={{display:"flex",justifyContent:"space-between"}}><span style={{color:"#fff",fontWeight:700,fontSize:11}}>{e.role}</span><span style={{color:"#818cf8",fontSize:9.5}}>{e.start}–{e.current?"now":e.end}</span></div><div style={{color:"#818cf8",fontSize:9.5,marginBottom:4}}>{e.company}</div><p style={{fontSize:10.5,color:"#94a3b8",lineHeight:1.65,margin:0}}>{e.description}</p></div>)}</div>}{cv.education?.length>0&&<div style={{marginBottom:16}}><div style={{fontSize:8.5,fontWeight:800,color:"#818cf8",textTransform:"uppercase",letterSpacing:3,marginBottom:9}}>Formation</div>{cv.education.map((e,i)=><div key={i} style={{fontSize:10.5,marginBottom:7}}><span style={{color:"#fff",fontWeight:600}}>{e.degree} {e.field}</span> · <span style={{color:"#818cf8"}}>{e.school}</span></div>)}</div>}{cv.skills&&<div style={{marginBottom:14}}><div style={{fontSize:8.5,fontWeight:800,color:"#818cf8",textTransform:"uppercase",letterSpacing:3,marginBottom:7}}>Skills</div><p style={{fontSize:10.5,color:"#94a3b8",margin:0}}>{cv.skills}</p></div>}<CVFooter cv={cv} a="#818cf8"/></div>;
}

/* ATS primitives */
const A = ({ label, color="#1c1812" }) => (
  <div style={{ fontSize:9, fontWeight:800, textTransform:"uppercase", letterSpacing:"3px",
    color, borderBottom:`2px solid ${color}`, paddingBottom:3, marginBottom:10, marginTop:16 }}>{label}</div>
);
const AExp = ({ e, accent }) => (
  <div style={{ marginBottom:12 }}>
    <div style={{ display:"flex", justifyContent:"space-between", alignItems:"baseline" }}>
      <strong style={{ fontSize:11.5, color:"#111" }}>{e.role}</strong>
      <span style={{ fontSize:9.5, color:"#666", whiteSpace:"nowrap", marginLeft:8 }}>{e.start}{e.end||e.current?` – ${e.current?"Présent":e.end}`:""}</span>
    </div>
    <div style={{ fontSize:10.5, color:accent, fontWeight:600, marginBottom:3 }}>{e.company}</div>
    <p style={{ fontSize:10.5, color:"#444", lineHeight:1.65, margin:0 }}>{e.description}</p>
  </div>
);
const AEdu = ({ e }) => (
  <div style={{ marginBottom:9 }}>
    <div style={{ display:"flex", justifyContent:"space-between", alignItems:"baseline" }}>
      <strong style={{ fontSize:11.5, color:"#111" }}>{e.degree}{e.field?` — ${e.field}`:""}</strong>
      <span style={{ fontSize:9.5, color:"#666" }}>{e.start}{e.end?` – ${e.end}`:""}</span>
    </div>
    <div style={{ fontSize:10.5, color:"#666" }}>{e.school}</div>
  </div>
);
const AFooter = ({ cv, accent }) => {
  const hasH = cv.hobbies?.filter(h=>h.label).length > 0;
  const hasR = cv.references?.filter(r=>r.name).length > 0;
  const hasSig = cv.signatureCity || cv.signatureDate;
  return (<>
    {hasH&&<><A label="Centres d'intérêt" color={accent}/><p style={{fontSize:10.5,color:"#444",lineHeight:1.7,margin:0}}>{cv.hobbies.filter(h=>h.label).map(h=>h.label).join("  ·  ")}</p></>}
    {cv.certifications?.trim()&&<><A label="Certifications" color={accent}/><p style={{fontSize:10.5,color:"#444",margin:0}}>{cv.certifications}</p></>}
    {cv.publications?.trim()&&<><A label="Publications & Projets" color={accent}/><p style={{fontSize:10.5,color:"#444",margin:0,whiteSpace:"pre-line"}}>{cv.publications}</p></>}
    {hasR&&<><A label="Références professionnelles" color={accent}/>{cv.references.filter(r=>r.name).map((r,i)=><div key={i} style={{marginBottom:8,fontSize:10.5}}><strong>{r.name}</strong>{r.role&&<span style={{color:accent}}> — {r.role}{r.company?`, ${r.company}`:""}</span>}{r.email&&<span style={{color:"#666"}}> · {r.email}</span>}{r.phone&&<span style={{color:"#666"}}> · {r.phone}</span>}</div>)}</>}
    {cv.refsOnRequest&&!hasR&&<p style={{fontSize:10,color:"#999",fontStyle:"italic",marginTop:8}}>Références disponibles sur demande.</p>}
    {hasSig&&<div style={{marginTop:24}}><div style={{fontSize:9.5,color:"#888",fontStyle:"italic",textAlign:"center",border:`1px solid ${accent}25`,borderRadius:5,padding:"6px 12px",marginBottom:16,lineHeight:1.6}}>Je déclare sur l'honneur que toutes ces informations sont sincères et vérifiables.</div><div style={{display:"flex",justifyContent:"flex-end"}}><div style={{textAlign:"right",fontSize:10.5,color:"#888"}}><div>{[cv.signatureCity,cv.signatureDate].filter(Boolean).join(", le ")}</div>{cv.signature?<img src={cv.signature} alt="Signature" style={{height:50,marginTop:8,display:"block",marginLeft:"auto"}}/>:<div style={{marginTop:24,borderTop:`1px solid ${accent}60`,paddingTop:4,minWidth:160,fontSize:10,color:"#aaa"}}>Signature</div>}</div></div></div>}
  </>);
};
const ATSWrap = ({ cv, accent="#1c1812", bg="#fff", children }) => (
  <div style={{ fontFamily:"'Arial',sans-serif", background:bg, color:"#1c1812", padding:"32px 38px", minHeight:680, maxWidth:"100%", position:"relative" }}>
    {children}
    {cv.experiences?.length>0&&<><A label="Expériences professionnelles" color={accent}/>{cv.experiences.map((e,i)=><AExp key={i} e={e} accent={accent}/>)}</>}
    {cv.education?.length>0&&<><A label="Formation" color={accent}/>{cv.education.map((e,i)=><AEdu key={i} e={e}/>)}</>}
    {cv.skills&&<><A label="Compétences" color={accent}/><p style={{fontSize:10.5,color:"#444",lineHeight:1.7,margin:0}}>{cv.skills}</p></>}
    {cv.languages&&<><A label="Langues" color={accent}/><p style={{fontSize:10.5,color:"#444",margin:0}}>{cv.languages}</p></>}
    <AFooter cv={cv} accent={accent}/>
  </div>
);

function ATSClarte({ cv }) {
  return (<ATSWrap cv={cv} accent="#1c1812"><div style={{borderBottom:"2px solid #1c1812",paddingBottom:14,marginBottom:4}}><div style={{fontSize:22,fontWeight:700,color:"#1c1812",letterSpacing:"-0.3px"}}>{fullName(cv)}</div><div style={{fontSize:12,color:"#444",marginTop:3}}>{cv.title}</div><div style={{fontSize:10,color:"#666",marginTop:6,lineHeight:1.8}}>{[cv.email,cv.phone,cv.location,cv.linkedin].filter(Boolean).join("   |   ")}</div></div>{cv.summary&&<><A label="Profil professionnel" color="#1c1812"/><p style={{fontSize:10.5,color:"#444",lineHeight:1.75,margin:0}}>{cv.summary}</p></>}</ATSWrap>);
}
function ATSDakar({ cv }) {
  const ACC="#7b2d2d";
  return (<ATSWrap cv={cv} accent={ACC}><div style={{borderLeft:`4px solid ${ACC}`,paddingLeft:16,marginBottom:4}}>{cv.photo&&<img src={cv.photo} alt="" style={{width:62,height:75,objectFit:"cover",float:"right",borderRadius:4,border:`2px solid ${ACC}30`}}/>}<div style={{fontSize:21,fontWeight:700,color:"#1c1812"}}>{fullName(cv)}</div><div style={{fontSize:11.5,color:ACC,fontWeight:600,marginTop:2}}>{cv.title}</div><div style={{fontSize:10,color:"#666",marginTop:6,lineHeight:1.9}}>{[cv.email,cv.phone,cv.location].filter(Boolean).map((v,i)=><div key={i}>{v}</div>)}</div><div style={{clear:"both"}}/></div>{cv.summary&&<><A label="Présentation" color={ACC}/><p style={{fontSize:10.5,color:"#444",lineHeight:1.75,margin:0}}>{cv.summary}</p></>}</ATSWrap>);
}
function ATSSahel({ cv }) {
  const ACC="#8b6914";
  return (<ATSWrap cv={cv} accent={ACC}><div style={{textAlign:"center",paddingBottom:14,marginBottom:4,borderBottom:`1px solid ${ACC}`}}>{cv.photo&&<img src={cv.photo} alt="" style={{width:62,height:75,objectFit:"cover",borderRadius:"50%",border:`2px solid ${ACC}`,marginBottom:8,display:"block",margin:"0 auto 8px"}}/>}<div style={{fontSize:22,fontWeight:700,letterSpacing:"1px",color:"#1c1812",textTransform:"uppercase"}}>{fullName(cv)}</div><div style={{fontSize:11,color:ACC,marginTop:4,fontStyle:"italic"}}>{cv.title}</div><div style={{fontSize:10,color:"#777",marginTop:6}}>{[cv.email,cv.phone,cv.location].filter(Boolean).join("   ·   ")}</div></div>{cv.summary&&<><A label="Profil" color={ACC}/><p style={{fontSize:10.5,color:"#444",lineHeight:1.75,margin:0,textAlign:"justify"}}>{cv.summary}</p></>}</ATSWrap>);
}
function ATSDiplomate({ cv }) {
  return (<div style={{fontFamily:"'Times New Roman',serif",background:"#fff",color:"#111",padding:"32px 38px",minHeight:680,position:"relative"}}><div style={{textAlign:"center",borderBottom:"1px solid #111",paddingBottom:12,marginBottom:4}}><div style={{fontSize:20,fontWeight:700,textTransform:"uppercase",letterSpacing:"2px"}}>{fullName(cv)}</div><div style={{fontSize:11,color:"#555",marginTop:3,fontStyle:"italic"}}>{cv.title}</div><div style={{fontSize:10,color:"#666",marginTop:6}}>{[cv.email,cv.phone,cv.location].filter(Boolean).join("   |   ")}</div></div>{cv.summary&&<><A label="Résumé" color="#111"/><p style={{fontSize:10.5,lineHeight:1.85,textAlign:"justify",margin:0}}>{cv.summary}</p></>}{cv.experiences?.length>0&&<><A label="Expériences professionnelles" color="#111"/>{cv.experiences.map((e,i)=><AExp key={i} e={e} accent="#111"/>)}</>}{cv.education?.length>0&&<><A label="Formation" color="#111"/>{cv.education.map((e,i)=><AEdu key={i} e={e}/>)}</>}{cv.skills&&<><A label="Compétences" color="#111"/><p style={{fontSize:10.5,margin:0}}>{cv.skills}</p></>}{cv.languages&&<><A label="Langues" color="#111"/><p style={{fontSize:10.5,margin:0}}>{cv.languages}</p></>}<AFooter cv={cv} accent="#111"/></div>);
}
function ATSIngenieur({ cv }) {
  const ACC="#1a3a5c";
  return (<ATSWrap cv={cv} accent={ACC}><div style={{background:ACC,color:"#fff",padding:"16px 20px",margin:"-32px -38px 4px",borderBottom:"3px solid #c49a3c"}}><div style={{fontSize:20,fontWeight:700}}>{fullName(cv)}</div><div style={{fontSize:11,color:"#a8c4e0",marginTop:2}}>{cv.title}</div><div style={{fontSize:10,color:"#7ca8cc",marginTop:6}}>{[cv.email,cv.phone,cv.location].filter(Boolean).join("   |   ")}</div></div><div style={{marginTop:20}}>{cv.summary&&<><A label="Profil technique" color={ACC}/><p style={{fontSize:10.5,color:"#444",lineHeight:1.75,margin:0}}>{cv.summary}</p></>}</div></ATSWrap>);
}
function ATSConsultant({ cv }) {
  const ACC="#1a4d3a";
  return (<ATSWrap cv={cv} accent={ACC}><div style={{display:"flex",justifyContent:"space-between",alignItems:"flex-start",borderBottom:`2px solid ${ACC}`,paddingBottom:14,marginBottom:4}}><div><div style={{fontSize:21,fontWeight:700,color:"#111"}}>{fullName(cv)}</div><div style={{fontSize:11.5,color:ACC,fontWeight:600,marginTop:2}}>{cv.title}</div></div><div style={{textAlign:"right",fontSize:10,color:"#666",lineHeight:2}}>{[cv.email,cv.phone,cv.location].filter(Boolean).map((v,i)=><div key={i}>{v}</div>)}</div></div>{cv.summary&&<><A label="Synthèse executive" color={ACC}/><p style={{fontSize:10.5,color:"#444",lineHeight:1.75,margin:0}}>{cv.summary}</p></>}</ATSWrap>);
}
function ATSAcademique({ cv }) {
  const ACC="#3b2f6b";
  return (<div style={{fontFamily:"'Georgia',serif",background:"#fff",color:"#111",padding:"32px 38px",minHeight:680,position:"relative"}}><div style={{textAlign:"center",borderBottom:`1.5px solid ${ACC}`,paddingBottom:14,marginBottom:4}}>{cv.photo&&<img src={cv.photo} alt="" style={{width:56,height:68,objectFit:"cover",borderRadius:4,float:"right"}}/>}<div style={{fontSize:20,fontWeight:700}}>{fullName(cv)}</div><div style={{fontSize:11,color:ACC,fontStyle:"italic",marginTop:3}}>{cv.title}</div><div style={{fontSize:10,color:"#666",marginTop:5}}>{[cv.email,cv.phone,cv.location].filter(Boolean).join("   |   ")}</div><div style={{clear:"both"}}/></div>{cv.summary&&<><A label="Résumé académique" color={ACC}/><p style={{fontSize:10.5,lineHeight:1.85,textAlign:"justify",margin:0}}>{cv.summary}</p></>}{cv.experiences?.length>0&&<><A label="Expériences d'enseignement & recherche" color={ACC}/>{cv.experiences.map((e,i)=><AExp key={i} e={e} accent={ACC}/>)}</>}{cv.education?.length>0&&<><A label="Formation académique" color={ACC}/>{cv.education.map((e,i)=><AEdu key={i} e={e}/>)}</>}{cv.skills&&<><A label="Domaines de recherche & compétences" color={ACC}/><p style={{fontSize:10.5,margin:0}}>{cv.skills}</p></>}{cv.languages&&<><A label="Langues" color={ACC}/><p style={{fontSize:10.5,margin:0}}>{cv.languages}</p></>}<AFooter cv={cv} accent={ACC}/></div>);
}
function ATSHumanitaire({ cv }) {
  const ACC="#c25e00";
  return (<ATSWrap cv={cv} accent={ACC}><div style={{borderBottom:`2px solid ${ACC}`,paddingBottom:14,marginBottom:4}}>{cv.photo&&<img src={cv.photo} alt="" style={{width:60,height:72,objectFit:"cover",float:"right",borderRadius:4}}/>}<div style={{fontSize:20,fontWeight:700}}>{fullName(cv)}</div><div style={{fontSize:11.5,color:ACC,fontWeight:600,marginTop:2}}>{cv.title}</div><div style={{fontSize:10,color:"#666",marginTop:6,lineHeight:1.9}}>{[cv.email,cv.phone,cv.location].filter(Boolean).map((v,i)=><div key={i}>{v}</div>)}</div><div style={{clear:"both"}}/></div>{cv.summary&&<><A label="Profil & engagements terrain" color={ACC}/><p style={{fontSize:10.5,color:"#444",lineHeight:1.75,margin:0}}>{cv.summary}</p></>}</ATSWrap>);
}
function ATSJunior({ cv }) {
  const ACC="#0e5a8a";
  return (<div style={{fontFamily:"'Arial',sans-serif",background:"#fff",color:"#1c1812",padding:"32px 38px",minHeight:680,position:"relative"}}><div style={{borderBottom:`3px solid ${ACC}`,paddingBottom:12,marginBottom:4}}><div style={{fontSize:20,fontWeight:700}}>{fullName(cv)}</div><div style={{fontSize:11.5,color:ACC,marginTop:2}}>{cv.title}</div><div style={{fontSize:10,color:"#666",marginTop:5}}>{[cv.email,cv.phone,cv.location].filter(Boolean).join("   |   ")}</div></div>{cv.summary&&<><A label="Objectif professionnel" color={ACC}/><p style={{fontSize:10.5,color:"#444",lineHeight:1.75,margin:0}}>{cv.summary}</p></>}{cv.education?.length>0&&<><A label="Formation" color={ACC}/>{cv.education.map((e,i)=><AEdu key={i} e={e}/>)}</>}{cv.experiences?.length>0&&<><A label="Expériences & stages" color={ACC}/>{cv.experiences.map((e,i)=><AExp key={i} e={e} accent={ACC}/>)}</>}{cv.skills&&<><A label="Compétences" color={ACC}/><p style={{fontSize:10.5,color:"#444",lineHeight:1.7,margin:0}}>{cv.skills}</p></>}{cv.languages&&<><A label="Langues" color={ACC}/><p style={{fontSize:10.5,color:"#444",margin:0}}>{cv.languages}</p></>}<AFooter cv={cv} accent={ACC}/></div>);
}
function ATSCadre({ cv }) {
  const ACC="#111";
  return (<div style={{fontFamily:"'Georgia',serif",background:"#fff",color:"#111",padding:"32px 38px",minHeight:680,position:"relative"}}><div style={{display:"flex",justifyContent:"space-between",alignItems:"flex-start",borderBottom:"2.5px solid #111",paddingBottom:14,marginBottom:4}}><div><div style={{fontSize:23,fontWeight:700,letterSpacing:"-0.5px"}}>{fullName(cv)}</div><div style={{fontSize:12,color:"#444",fontStyle:"italic",marginTop:3}}>{cv.title}</div></div>{cv.photo&&<img src={cv.photo} alt="" style={{width:60,height:72,objectFit:"cover",borderRadius:3,border:"1px solid #ddd"}}/>}</div><div style={{display:"flex",gap:20,fontSize:10,color:"#666",marginBottom:4,marginTop:10}}>{[cv.email,cv.phone,cv.location].filter(Boolean).map((v,i)=><span key={i}>{v}</span>)}</div>{cv.summary&&<><A label="Profil exécutif" color={ACC}/><p style={{fontSize:10.5,lineHeight:1.8,margin:0,fontStyle:"italic",color:"#333"}}>{cv.summary}</p></>}{cv.experiences?.length>0&&<><A label="Parcours professionnel" color={ACC}/>{cv.experiences.map((e,i)=><AExp key={i} e={e} accent={ACC}/>)}</>}{cv.education?.length>0&&<><A label="Formation" color={ACC}/>{cv.education.map((e,i)=><AEdu key={i} e={e}/>)}</>}{cv.skills&&<><A label="Compétences clés" color={ACC}/><p style={{fontSize:10.5,margin:0}}>{cv.skills}</p></>}{cv.languages&&<><A label="Langues" color={ACC}/><p style={{fontSize:10.5,margin:0}}>{cv.languages}</p></>}<AFooter cv={cv} accent={ACC}/></div>);
}

const RENDERERS = { executive:CVExecutive,tech:CVTech,creative:CVCreative,minimal:CVMinimal,corporate:CVCorporate,academic:CVAcademic,medical:CVMedical,legal:CVLegal,marketing:CVMarketing,startup:CVStartup };
const ATS_RENDERERS = { "ats-clarte":ATSClarte,"ats-dakar":ATSDakar,"ats-sahel":ATSSahel,"ats-diplomate":ATSDiplomate,"ats-ingenieur":ATSIngenieur,"ats-consultant":ATSConsultant,"ats-academique":ATSAcademique,"ats-humanitaire":ATSHumanitaire,"ats-junior":ATSJunior,"ats-cadre":ATSCadre };


export { CVFooter, CVExecutive, CVTech, CVCreative, CVMinimal, CVCorporate,
  CVAcademic, CVMedical, CVLegal, CVMarketing, CVStartup,
  ATSClarte, ATSDakar, ATSSahel, ATSDiplomate, ATSIngenieur,
  ATSConsultant, ATSAcademique, ATSHumanitaire, ATSJunior, ATSCadre,
  RENDERERS, ATS_RENDERERS };
